[features]
seeds = false
[programs.localnet]
plats_solana = "3oj39XhPhs68TSn1JvLsavK1CG4NyQW7TG6R9EuE68Ze"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/trungtin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
